FROM python:3.9-slim
WORKDIR /app
COPY app.py .
COPY requirements.txt .
RUN apt-get update && apt-get install -y iproute2
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "-u", "app.py"]